import React from 'react'
import './Grid.css'

const Grid = () => (
    <main>
        <section>col 1</section>
        <section>col 2</section>
        <section>col 3</section>
        <section>col 4</section>
        <section>col 5</section>
        <section>col 6</section>
        <section>col 7</section>
        <section>col 8</section>
        <section>col 9</section>
        <section>col 10</section>
        <section>col 11</section>
        <section>col 12</section>
        <section>col 13</section>
        <section>col 14</section>
        <section>col 15</section>
        <section>col 16</section>
        <section>col 17</section>
        <section>col 18</section>
        <section>col 19</section>
        <section>col 20</section>
        <section>col 21</section>
        <section>col 22</section>
        <section>col 23</section>
        <section>col 24</section>
        <section>col 25</section>
        <section>col 26</section>
        <section>col 27</section>
        <section>col 28</section>
        <section>col 29</section>
        <section>col 30</section>
        <section>col 31</section>
        <section>col 32</section>
        <section>col 33</section>
        <section>col 34</section>
        <section>col 35</section>
        <section>col 36</section>
        <section>col 37</section>
        <section>col 38</section>
        <section>col 39</section>
        <section>col 40</section>
        <section>col 41</section>
        <section>col 42</section>
        <section>col 43</section>
        <section>col 44</section>
        <section>col 45</section>
        <section>col 46</section>
        <section>col 47</section>
        <section>col 48</section>
        <section>col 49</section>
        <section>col 50</section>
        <section>col 51</section>
        <section>col 52</section>
        <section>col 53</section>
        <section>col 54</section>
        <section>col 55</section>
        <section>col 56</section>
        <section>col 57</section>
        <section>col 58</section>
        <section>col 59</section>
        <section>col 60</section>
        <section>col 61</section>
        <section>col 62</section>
        <section>col 63</section>
        <section>col 64</section>
        <section>col 65</section>
        <section>col 66</section>
        <section>col 67</section>
        <section>col 68</section>
        <section>col 69</section>
        <section>col 70</section>
        <section>col 71</section>
        <section>col 72</section>
        <section>col 73</section>
        <section>col 74</section>
        <section>col 75</section>
        <section>col 76</section>
        <section>col 77</section>
        <section>col 78</section>
        <section>col 79</section>
        <section>col 80</section>
        <section>col 81</section>
        <section>col 82</section>
        <section>col 83</section>
        <section>col 84</section>
        <section>col 85</section>
        <section>col 86</section>
        <section>col 87</section>
        <section>col 88</section>
        <section>col 89</section>
        <section>col 90</section>
        <section>col 91</section>
        <section>col 92</section>
        <section>col 93</section>
        <section>col 94</section>
        <section>col 95</section>
        <section>col 96</section>
        <section>col 97</section>
        <section>col 98</section>
        <section>col 99</section>
        <section>col 100</section>
        <section>col 101</section>
        <section>col 102</section>
        <section>col 103</section>
        <section>col 104</section>
        <section>col 105</section>
        <section>col 106</section>
        <section>col 107</section>
        <section>col 108</section>
        <section>col 109</section>
        <section>col 110</section>
        <section>col 111</section>
        <section>col 112</section>
        <section>col 113</section>
        <section>col 114</section>
        <section>col 115</section>
        <section>col 116</section>
        <section>col 117</section>
        <section>col 118</section>
        <section>col 119</section>
        <section>col 120</section>
        <section>col 121</section>
        <section>col 122</section>
        <section>col 123</section>
        <section>col 124</section>
        <section>col 125</section>
        <section>col 126</section>
        <section>col 127</section>
        <section>col 128</section>
        <section>col 129</section>
        <section>col 130</section>
        <section>col 131</section>
        <section>col 132</section>
        <section>col 133</section>
        <section>col 134</section>
        <section>col 135</section>
        <section>col 136</section>
        <section>col 137</section>
        <section>col 138</section>
        <section>col 139</section>
        <section>col 140</section>
        <section>col 141</section>
        <section>col 142</section>
        <section>col 143</section>
        <section>col 144</section>
        <section>col 145</section>
        <section>col 146</section>
        <section>col 147</section>
        <section>col 148</section>
        <section>col 149</section>
        <section>col 150</section>
        <section>col 151</section>
        <section>col 152</section>
        <section>col 153</section>
        <section>col 154</section>
        <section>col 155</section>
        <section>col 156</section>
        <section>col 157</section>
        <section>col 158</section>
        <section>col 159</section>
        <section>col 160</section>
        <section>col 161</section>
        <section>col 162</section>
        <section>col 163</section>
        <section>col 164</section>
        <section>col 165</section>
        <section>col 166</section>
        <section>col 167</section>
        <section>col 168</section>
        <section>col 169</section>
        <section>col 170</section>
        <section>col 171</section>
        <section>col 172</section>
        <section>col 173</section>
        <section>col 174</section>
        <section>col 175</section>
        <section>col 176</section>
        <section>col 177</section>
        <section>col 178</section>
        <section>col 179</section>
        <section>col 180</section>
        <section>col 181</section>
        <section>col 182</section>
        <section>col 183</section>
        <section>col 184</section>
        <section>col 185</section>
        <section>col 186</section>
        <section>col 187</section>
        <section>col 188</section>
        <section>col 189</section>
        <section>col 190</section>
        <section>col 191</section>
        <section>col 192</section>
        <section>col 193</section>
        <section>col 194</section>
        <section>col 195</section>
        <section>col 196</section>
        <section>col 197</section>
        <section>col 198</section>
        <section>col 199</section>
        <section>col 200</section>
        <section>col 201</section>
        <section>col 202</section>
        <section>col 203</section>
        <section>col 204</section>
        <section>col 205</section>
        <section>col 206</section>
        <section>col 207</section>
        <section>col 208</section>
        <section>col 209</section>
        <section>col 210</section>
        <section>col 211</section>
        <section>col 212</section>
        <section>col 213</section>
        <section>col 214</section>
        <section>col 215</section>
        <section>col 216</section>
        <section>col 217</section>
        <section>col 218</section>
        <section>col 219</section>
        <section>col 220</section>
        <section>col 221</section>
        <section>col 222</section>
        <section>col 223</section>
        <section>col 224</section>
        <section>col 225</section>
        <section>col 226</section>
        <section>col 227</section>
        <section>col 228</section>
        <section>col 229</section>
        <section>col 230</section>
        <section>col 231</section>
        <section>col 232</section>
        <section>col 233</section>
        <section>col 234</section>
        <section>col 235</section>
        <section>col 236</section>
        <section>col 237</section>
        <section>col 238</section>
        <section>col 239</section>
        <section>col 240</section>
        <section>col 241</section>
        <section>col 242</section>
        <section>col 243</section>
        <section>col 244</section>
        <section>col 245</section>
        <section>col 246</section>
        <section>col 247</section>
        <section>col 248</section>
        <section>col 249</section>
        <section>col 250</section>
        <section>col 251</section>
        <section>col 252</section>
        <section>col 253</section>
        <section>col 254</section>
        <section>col 255</section>
        <section>col 256</section>
        <section>col 257</section>
        <section>col 258</section>
        <section>col 259</section>
        <section>col 260</section>
        <section>col 261</section>
        <section>col 262</section>
        <section>col 263</section>
        <section>col 264</section>
        <section>col 265</section>
        <section>col 266</section>
        <section>col 267</section>
        <section>col 268</section>
        <section>col 269</section>
        <section>col 270</section>
        <section>col 271</section>
        <section>col 272</section>
        <section>col 273</section>
        <section>col 274</section>
        <section>col 275</section>
        <section>col 276</section>
        <section>col 277</section>
        <section>col 278</section>
        <section>col 279</section>
        <section>col 280</section>
        <section>col 281</section>
        <section>col 282</section>
        <section>col 283</section>
        <section>col 284</section>
        <section>col 285</section>
        <section>col 286</section>
        <section>col 287</section>
        <section>col 288</section>
        <section>col 289</section>
        <section>col 290</section>
        <section>col 291</section>
        <section>col 292</section>
        <section>col 293</section>
        <section>col 294</section>
        <section>col 295</section>
        <section>col 296</section>
        <section>col 297</section>
        <section>col 298</section>
        <section>col 299</section>
        <section>col 300</section>
    </main>
)

export default Grid